# Generated by Django 5.1 on 2024-11-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='img',
            field=models.CharField(blank=True, default='http://www.fillster.com/images/pictures/10p.jpg', max_length=9999),
        ),
    ]
