# Generated by Django 5.1 on 2024-11-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='img',
            field=models.CharField(blank=True, default='https://www.contentviewspro.com/wp-content/uploads/2017/07/default_image.png', max_length=9999),
        ),
    ]
