# Generated by Django 5.1 on 2024-11-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_won'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='won',
        ),
        migrations.AddField(
            model_name='listing',
            name='inactive',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
